"""Added users table

Revision ID: 08edc096bc8f
Revises: d6abe79eec68
Create Date: 2023-07-18 06:43:43.085158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08edc096bc8f'
down_revision = 'd6abe79eec68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
