"""Added mfa fields to the user table

Revision ID: caa22988e3ad
Revises: 08edc096bc8f
Create Date: 2023-09-09 15:53:20.811274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa22988e3ad'
down_revision = '08edc096bc8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_enabled', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('otp_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('otp_base32', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('otp_auth_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('otp_enabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_enabled_at')
    op.drop_column('user', 'otp_auth_url')
    op.drop_column('user', 'otp_base32')
    op.drop_column('user', 'otp_verified')
    op.drop_column('user', 'otp_enabled')
    # ### end Alembic commands ###
