"""Added profile path to users table

Revision ID: ddf2990c91dc
Revises: 08edc096bc8f
Create Date: 2023-09-22 15:40:00.949034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf2990c91dc'
down_revision = '08edc096bc8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_path')
    # ### end Alembic commands ###
