version: '3.9'
services:

  users:
    container_name: users
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app/:/app
    command: uvicorn app.app:app --host 0.0.0.0 --port 80 --reload

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: