from enum import Enum


class ErrorCode(str, Enum):
    REGISTER_INVALID_NAME = "REGISTER_INVALID_NAME"
    INVALID_OTP_TOKEN = "INVALID_OTP_TOKEN"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    INVALID_FILE_SIZE = "INVALID_FILE_SIZE"
