---
name: FastAPI Core CI
on: [pull_request]

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Python 3.9
            uses: actions/setup-python@v4
            with:
              python-version: 3.9
              
          - name: Lint with flake8
            uses: py-actions/flake8@v2
            with:
              max-line-length: 120

          - name: Run linters
            uses: wearerequired/lint-action@v2
            with:
              autopep8: true
              autopep8_auto_fix: true
